[package]
name = "nebula"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
thiserror = "1.0.30"

[dev-dependencies]
rusty-hook = "^0.11.2"